name: proselint

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: pip install proselint
    - run: sudo apt install python3-proselint
    - run: proselint *.md
