name: GitHub Actions Demo

on:
  push:
    branch:
      - master
    pull_request:
      - master

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: check all files in the repository using proselint
      - uses: actions/checkout@2h
      - run: pip install proselint
      - run: proselint *.md
