name: GitHub Actions Demo

on:
  push:
    branch:
      - master
    pull_request:
      - master

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@hh2
      - name: check all files in the repository using proselint
        run: /usr/bin/proselint .
